# -*- coding: utf-8 -*-
"""word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tensorflow/text/blob/master/docs/tutorials/word2vec.ipynb

##### Copyright 2020 The TensorFlow Authors.
"""

import os

os.environ["TF_USE_LEGACY_KERAS"] = "1"
import io
import re
import string

import numpy as np
import tensorflow as tf
from absl import flags
from packaging.version import parse
from tensorflow.keras import layers

import deepray as dp
from dataset import generate_training_data
from model import Word2Vec
from deepray.core.trainer import Trainer

AUTOTUNE = tf.data.AUTOTUNE

"""### Vectorize an example sentence

Consider the following sentence:

> The wide road shimmered in the hot sun.

Tokenize the sentence:
"""

sentence = "The wide road shimmered in the hot sun"
tokens = list(sentence.lower().split())
print(len(tokens))

"""Create a vocabulary to save mappings from tokens to integer indices:"""

vocab, index = {}, 1  # start indexing from 1
vocab["<pad>"] = 0  # add a padding token
for token in tokens:
  if token not in vocab:
    vocab[token] = index
    index += 1
vocab_size = len(vocab)
print(vocab)

"""Create an inverse vocabulary to save mappings from integer indices to tokens:"""

inverse_vocab = {index: token for token, index in vocab.items()}
print(inverse_vocab)

"""Vectorize your sentence:"""

example_sequence = [vocab[word] for word in tokens]
print(example_sequence)

"""### Generate skip-grams from one sentence

The `tf.keras.preprocessing.sequence` module provides useful functions that simplify data preparation for word2vec. You can use the `tf.keras.preprocessing.sequence.skipgrams` to generate skip-gram pairs from the `example_sequence` with a given `window_size` from tokens in the range `[0, vocab_size)`.

Note: `negative_samples` is set to `0` here, as batching negative samples generated by this function requires a bit of code. You will use another function to perform negative sampling in the next section.
"""

window_size = 2
positive_skip_grams, _ = tf.keras.preprocessing.sequence.skipgrams(
  example_sequence, vocabulary_size=vocab_size, window_size=window_size, negative_samples=0
)
print(len(positive_skip_grams))

"""Print a few positive skip-grams:"""

for target, context in positive_skip_grams[:5]:
  print(f"({target}, {context}): ({inverse_vocab[target]}, {inverse_vocab[context]})")

"""### Negative sampling for one skip-gram

The `skipgrams` function returns all positive skip-gram pairs by sliding over a given window span. To produce additional skip-gram pairs that would serve as negative samples for training, you need to sample random words from the vocabulary. Use the `tf.random.log_uniform_candidate_sampler` function to sample `num_ns` number of negative samples for a given target word in a window. You can call the function on one skip-grams's target word and pass the context word as true class to exclude it from being sampled.

Key point: `num_ns` (the number of negative samples per a positive context word) in the `[5, 20]` range is [shown to work](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf) best for smaller datasets, while `num_ns` in the `[2, 5]` range suffices for larger datasets.
"""

# Get target and context words for one positive skip-gram.
target_word, context_word = positive_skip_grams[0]

# Set the number of negative samples per positive context.
num_ns = 4

context_class = tf.reshape(tf.constant(context_word, dtype="int64"), (1, 1))
negative_sampling_candidates, _, _ = tf.random.log_uniform_candidate_sampler(
  true_classes=context_class,  # class that should be sampled as 'positive'
  num_true=1,  # each positive skip-gram has 1 positive context class
  num_sampled=num_ns,  # number of negative context words to sample
  unique=True,  # all the negative samples should be unique
  range_max=vocab_size,  # pick index of the samples from [0, vocab_size]
  seed=flags.FLAGS.random_seed,  # seed for reproducibility
  name="negative_sampling",  # name of this operation
)
print(negative_sampling_candidates)
print([inverse_vocab[index.numpy()] for index in negative_sampling_candidates])

"""### Construct one training example

For a given positive `(target_word, context_word)` skip-gram, you now also have `num_ns` negative sampled context words that do not appear in the window size neighborhood of `target_word`. Batch the `1` positive `context_word` and `num_ns` negative context words into one tensor. This produces a set of positive skip-grams (labeled as `1`) and negative samples (labeled as `0`) for each target word.
"""

# Reduce a dimension so you can use concatenation (in the next step).
squeezed_context_class = tf.squeeze(context_class, 1)

# Concatenate a positive context word with negative sampled words.
context = tf.concat([squeezed_context_class, negative_sampling_candidates], 0)

# Label the first context word as `1` (positive) followed by `num_ns` `0`s (negative).
label = tf.constant([1] + [0] * num_ns, dtype="int64")
target = target_word

"""Check out the context and the corresponding labels for the target word from the skip-gram example above:"""

print(f"target_index    : {target}")
print(f"target_word     : {inverse_vocab[target_word]}")
print(f"context_indices : {context}")
print(f"context_words   : {[inverse_vocab[c.numpy()] for c in context]}")
print(f"label           : {label}")

"""A tuple of `(target, context, label)` tensors constitutes one training example for training your skip-gram negative sampling word2vec model. Notice that the target is of shape `(1,)` while the context and label are of shape `(1+num_ns,)`"""

print("target  :", target)
print("context :", context)
print("label   :", label)


sampling_table = tf.keras.preprocessing.sequence.make_sampling_table(size=10)
print(sampling_table)


path_to_file = tf.keras.utils.get_file(
  "shakespeare.txt", "https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt"
)

"""Read the text from the file and print the first few lines:"""

with open(path_to_file) as f:
  lines = f.read().splitlines()
for line in lines[:20]:
  print(line)

"""Use the non empty lines to construct a `tf.data.TextLineDataset` object for the next steps:"""

text_ds = tf.data.TextLineDataset(path_to_file).filter(lambda x: tf.cast(tf.strings.length(x), bool))

"""### Vectorize sentences from the corpus

You can use the `TextVectorization` layer to vectorize sentences from the corpus. Learn more about using this layer in this [Text classification](https://www.tensorflow.org/tutorials/keras/text_classification) tutorial. Notice from the first few sentences above that the text needs to be in one case and punctuation needs to be removed. To do this, define a `custom_standardization function` that can be used in the TextVectorization layer.
"""


# Now, create a custom standardization function to lowercase the text and
# remove punctuation.
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  return tf.strings.regex_replace(lowercase, "[%s]" % re.escape(string.punctuation), "")


# Define the vocabulary size and the number of words in a sequence.
vocab_size = 4096
sequence_length = 10

# Use the `TextVectorization` layer to normalize, split, and map strings to
# integers. Set the `output_sequence_length` length to pad all samples to the
# same length.
vectorize_layer = layers.TextVectorization(
  standardize=custom_standardization, max_tokens=vocab_size, output_mode="int", output_sequence_length=sequence_length
)

"""Call `TextVectorization.adapt` on the text dataset to create vocabulary.

"""

vectorize_layer.adapt(text_ds.batch(1024))

"""Once the state of the layer has been adapted to represent the text corpus, the vocabulary can be accessed with `TextVectorization.get_vocabulary`. This function returns a list of all vocabulary tokens sorted (descending) by their frequency."""

# Save the created vocabulary for reference.
inverse_vocab = vectorize_layer.get_vocabulary()
print(inverse_vocab[:20])

"""The `vectorize_layer` can now be used to generate vectors for each element in the `text_ds` (a `tf.data.Dataset`). Apply `Dataset.batch`, `Dataset.prefetch`, `Dataset.map`, and `Dataset.unbatch`."""

# Vectorize the data in text_ds.
text_vector_ds = text_ds.batch(1024).prefetch(AUTOTUNE).map(vectorize_layer).unbatch()

"""### Obtain sequences from the dataset

You now have a `tf.data.Dataset` of integer encoded sentences. To prepare the dataset for training a word2vec model, flatten the dataset into a list of sentence vector sequences. This step is required as you would iterate over each sentence in the dataset to produce positive and negative examples.

Note: Since the `generate_training_data()` defined earlier uses non-TensorFlow Python/NumPy functions, you could also use a `tf.py_function` or `tf.numpy_function` with `tf.data.Dataset.map`.
"""

sequences = list(text_vector_ds.as_numpy_iterator())
print(len(sequences))

"""Inspect a few examples from `sequences`:"""

for seq in sequences[:5]:
  print(f"{seq} => {[inverse_vocab[i] for i in seq]}")

"""### Generate training examples from sequences

`sequences` is now a list of int encoded sentences. Just call the `generate_training_data` function defined earlier to generate training examples for the word2vec model. To recap, the function iterates over each word from each sequence to collect positive and negative context words. Length of target, contexts and labels should be the same, representing the total number of training examples.
"""

targets, contexts, labels = generate_training_data(
  sequences=sequences, window_size=2, num_ns=4, vocab_size=vocab_size, seed=flags.FLAGS.random_seed
)

targets = np.array(targets)
contexts = np.array(contexts)
labels = np.array(labels)

print("\n")
print(f"targets.shape: {targets.shape}")
print(f"contexts.shape: {contexts.shape}")
print(f"labels.shape: {labels.shape}")

"""### Configure the dataset for performance

To perform efficient batching for the potentially large number of training examples, use the `tf.data.Dataset` API. After this step, you would have a `tf.data.Dataset` object of `(target_word, context_word), (label)` elements to train your word2vec model!
"""

BUFFER_SIZE = 10000
dataset = tf.data.Dataset.from_tensor_slices(((targets, contexts), labels))
dataset = dataset.shuffle(BUFFER_SIZE).batch(flags.FLAGS.batch_size, drop_remainder=True)
print(dataset)

"""Apply `Dataset.cache` and `Dataset.prefetch` to improve performance:"""

dataset = dataset.cache().prefetch(buffer_size=AUTOTUNE)
print(dataset)


embedding_dim = 128
word2vec = Word2Vec(vocab_size, embedding_dim)
if os.getenv("USE_TF") == "1":
  optimizer = "adam"
  # if parse(dp.__version__) < parse("0.21.95"):
  #   from tensorflow.keras import optimizers as keras_optimizers
  # else:
  #   from tf_keras import optimizers as keras_optimizers

  # optimizer = keras_optimizers.legacy.Adam(learning_rate=flags.FLAGS.learning_rate)
elif flags.FLAGS.use_dynamic_embedding:
  from tensorflow_recommenders_addons import dynamic_embedding as de

  if parse(dp.__version__) < parse("0.21.95"):
    from tensorflow.keras import optimizers as keras_optimizers
  else:
    from tf_keras import optimizers as keras_optimizers

  optimizer = keras_optimizers.legacy.Adam(learning_rate=flags.FLAGS.learning_rate)
  # optimizer = dp.optimizers.Adam(learning_rate=flags.FLAGS.learning_rate)
  optimizer = de.DynamicEmbeddingOptimizer(
    optimizer,
    #  synchronous=flags.FLAGS.use_horovod
  )
else:
  optimizer = dp.optimizers.Adam(learning_rate=flags.FLAGS.learning_rate)

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="logs")
if os.getenv("USE_DP") == "1":
  trainer = Trainer(
    model=word2vec,
    optimizer=optimizer,
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
    run_eagerly=flags.FLAGS.run_eagerly,
  )
  trainer.fit(dataset, epochs=20, callbacks=[tensorboard_callback])
else:
  word2vec.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
    run_eagerly=flags.FLAGS.run_eagerly,
    # use_legacy_optimizer=True
  )
  word2vec.fit(dataset, epochs=20, callbacks=[tensorboard_callback])

weights = word2vec.get_layer("w2v_embedding").get_weights()[0]
vocab = vectorize_layer.get_vocabulary()

"""Create and save the vectors and metadata files:"""

out_v = io.open("vectors.tsv", "w", encoding="utf-8")
out_m = io.open("metadata.tsv", "w", encoding="utf-8")

for index, word in enumerate(vocab):
  if index == 0:
    continue  # skip 0, it's padding.
  vec = weights[index]
  out_v.write("\t".join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()
