name: GitHub CI

on:
  push:
    branches:
      - main
      - r*
  pull_request:
    branches:
      - main
      - r*

jobs:
  nbfmt:
    name: Notebook format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
    - uses: actions/checkout@v2
    - name: Install tensorflow-docs
      run: python3 -m pip install -U git+https://github.com/tensorflow/docs
    - name: Check notebook formatting
      run: |
        # Run on all notebooks to prevent upstream change.
        echo "Check formatting with nbfmt:"
        python3 -m tensorflow_docs.tools.nbfmt --test \
            $(find docs/tutorials/ -type f -name *.ipynb)
  nblint:
    name: Notebook lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
    - uses: actions/checkout@v2
    - name: Install tensorflow-docs
      run: python3 -m pip install -U git+https://github.com/tensorflow/docs
    - name: Lint notebooks
      run: |
        # Run on all notebooks to prevent upstream change.
        echo "Lint check with nblint:"
        python3 -m tensorflow_docs.tools.nblint \
            --arg=repo:tensorflow/deepray \
            $(find docs/tutorials/ -type f -name *.ipynb ! -path "docs/tutorials/_template.ipynb")
